<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251207033806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fee_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, amount_amount INT NOT NULL, amount_currency VARCHAR(3) NOT NULL, structure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_760D29E62534008B ON fee_item (structure_id)');
        $this->addSql('CREATE TABLE fee_structure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE fee_item ADD CONSTRAINT FK_760D29E62534008B FOREIGN KEY (structure_id) REFERENCES fee_structure (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fee_item DROP CONSTRAINT FK_760D29E62534008B');
        $this->addSql('DROP TABLE fee_item');
        $this->addSql('DROP TABLE fee_structure');
    }
}
